# Generated by Django 5.2.7 on 2025-10-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
