# Generated by Django 5.2.7 on 2025-11-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_blog_alter_category_options_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
