# Generated by Django 5.2.7 on 2025-11-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
